
development:
  adapter: postgresql
  encoding: unicode
  database: MeHungryNow_development
  pool: 5
  username: traviata

test:
  adapter: postgresql
  encoding: unicode
  database: MeHungryNow_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: MeHungryNow_production
  pool: 5

